In [27]:
import requests
from bs4 import BeautifulSoup as bs
from IPython.core.display import HTML
import pandas as pd

In [28]:
URL = 'https://statmando.com/stats/career-dgpt-stats-mpo'

response = requests.get(URL)

In [29]:
response.status_code

200

In [30]:
response.text ##call URL html and show as text
soup = bs(response.text) ##soupify response
print(soup.prettify()) ##print in a more readable form

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   Career Standard DGPT Elite Stats MPO | StatMando StatZone | StatMando - Disc Golf's Statistics Platform
  </title>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, maximum-scale=3, minimum-scale=1, user-scalable=yes" name="viewport"/>
  <link href="/images/logo.png" rel="shortcut icon" type="image/png"/>
  <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://cdn.datatables.net/v/dt/dt-1.10.24/b-1.7.0/b-colvis-1.7.0/date-1.0.3/fh-3.1.8/datatables.min.css" rel="stylesheet" type="text/css"/>
  <link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css" media="all" rel="stylesheet" type="text/css"/>
  <style>
  </style>
  <link href="/css/app.css?id=4e84d778ea0d5a252ba8" rel="stylesheet"/>
  <meta content="Career Standard DGPT Elite Stats MPO | StatMando StatZone" property="og:title"/>
  <meta content="" property="og:description"/>
  <meta content="https://statmando.com/images/og_images/stats.jpg" id="og_image" property="og:image"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="Career Standard DGPT Elite Stats MPO | StatMando StatZone" name="twitter:title"/>
  <meta content="" name="twitter:description"/>
  <meta content="@statmando" name="twitter:creator"/>
  <meta content="@statmando" name="twitter:site"/>
  <script defer="" src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js">
  </script>
  <script src="/js/app.js?id=514f54df4bb93795c380">
  </script>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WM7ZBVS');
  </script>
  <!-- End Google Tag Manager -->
  <script src="https://code.jquery.com/jquery-3.5.1.js">
  </script>
  <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js">
  </script>
  <script src="https://cdn.datatables.net/v/dt/dt-1.10.24/b-1.7.0/b-colvis-1.7.0/date-1.0.3/fh-3.1.8/datatables.min.js" type="text/javascript">
  </script>
  <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js">
  </script>
  <script>
   function add_dropdown(column) {
            var colData = column.data().unique();
            var filterTarget = $(column.header()).attr('data-filter-target');
            var select = $('<select class="text-sm" style="padding-left: .5rem; padding-right: 2rem;"><option value="">[all]</option></select>')
                .appendTo($('#' + filterTarget))
                .on('change', function() {
                    var val = $(this).val()
                    val = $.fn.dataTable.util.escapeRegex(val);
                    column.search(val ? '^' + val + '$' : '', true, false).draw();
                });

            colData.sort().each(function(d, j) {
                if (!d.trim()) {
                    return;
                }

                select.append('<option value="' + d + '">' + d + '</option>')
            });
        }

        function add_search_math(column, id) {
            var filterTarget = $(column.header()).attr('data-filter-target');
            var select = $('<input type="text" id="search_math_' + id + '" size=4 placeholder="<, >, =" class="py-2 px-4 text-sm rounded" value=""/>')
                .appendTo($('#' + filterTarget))
        }

        const searchMathPlugin = function(settings, data, dataIndex) {
            var ret = true; // ret is our complete ROW T/F boolean
            var values = [];

            var index = -1;
            $('.filters').each(function() {
                index++;
                var target = $(this).attr('data-filter-target');
                var val = $('#search_math_' + target).val();
                values[index] = val;
            });

            var index = -1;
            $('.filters').each(function() {
                index++;

                if (settings.aoColumns[index].filter != 'search_math') {
                    return; // this is a CONTINUE
                }

                // this has to be the current header, not the current place we are typing...
                var val = values[index]; // $('#search_math_' + $(this).attr('data-filter-target')).val();

                if (val.length < 2) {
                    // don't change ret
                    return; // this is a CONTINUE
                }

                if (!searchMath(val, data[index])) {
                    ret = false;
                    return false; // BREAK we're done, can't show this row
                }
            });

            // this is whether we show the row or not true, show, false don't show
            return ret;
        }

        const searchMath = function(val, colVal) {
            //colVal = parseInt(colVal);
            colVal = parseFloat(colVal);

            var operator = val.trim().substr(0, 1);
            val = parseInt(val.substr(1).trim());

            switch (operator) {
                case '>':
                    return colVal > val ? true : false;
                    break;
                case '=':
                    return val == colVal ? true : false;
                    break;
                case '<':
                    return colVal < val ? true : false;
                    break;
                default:
                    throw new Error('invalid operator: the first character must be >, < or =, do something like: ">3000"');
                    break;
            }
        }

        $(document).ready(function() {
            var table = $('table#stats').DataTable({
                pageLength: 1000,
                dom: "ift",
                //fixedHeader: true,
                order: [], // "don't re-order when first loading"
                initComplete: function() {
                    this.api().columns().every(function(index) {
                        var id = $(this.header()).attr('data-filter-target');
                        var filter = $(this.header()).attr('data-filter');
                        var title = $(this.header()).text().trim();

                        if (filter === '') {
                            return;
                        }

                        if (filter === 'dropdown') {
                            add_dropdown(this);
                        }

                        if (filter === 'search_math') {
                            add_search_math(this, id);
                        }

                    });
                }
            });

            $.fn.dataTable.ext.search.push(searchMathPlugin);

            $('.filter-search_math input').on('keyup', function() {
                var val = $(this).val()

                if (val.length < 2) {
                    return;
                }

                table.draw();
            });
        });
  </script>
 </head>
 <body class="-disabled-antialiased">
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM7ZBVS" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <div class="flex flex-col h-screen w-full">
   <header class="fixed w-full">
    <nav class="flex items-center justify-between flex-wrap p-2 md:p-4 border-t-8 border-green-800" style="background-color: #323232">
     <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a href="/">
       <img class="object-contain h-8" src="/images/logo-banner.png"/>
      </a>
     </div>
     <div class="block md:hidden" id="nav" x-data="{ showMenu: false }">
      <button class="items-center px-3 py-2 border rounded hover:text-white hover:border-white">
       <svg class="text-white fill-current h-3 w-3" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <title>
         Menu
        </title>
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
        </path>
       </svg>
      </button>
      <div class="relative">
       <div class="flex flex-col bg-white absolute right-0 px-4" style="display: none;" x-show="showMenu">
        <!-- mobile menu -->
        <a class="border-b border-neutral-100 whitespace-nowrap py-4" href="/">
         Home
        </a>
        <a class="text-white bg-orange-600 hover:bg-orange-700 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold font-xs" href="/rankings/">
         Rankings
        </a>
        <a class="text-white bg-green-800 hover:bg-green-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/players/">
         Player Profiles
        </a>
        <a class="text-white bg-red-800 hover:bg-red-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/monday/">
         Monday
        </a>
        <a class="text-white bg-blue-800 hover:bg-blue-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/head-to-head">
         Head-to-Head
        </a>
        <a class="text-white bg-purple-800 hover:bg-purple-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/stats/">
         StatZone
        </a>
        <a class="border-b border-neutral-100 whitespace-nowrap py-4" href="/data-fix/">
         Data Fix Portal
        </a>
        <a class="border-b border-neutral-100 whitespace-nowrap py-4" href="/contact-us/">
         Contact Us
        </a>
        <a class="border-b border-neutral-100 whitespace-nowrap py-4" href="/about-us/">
         About Us
        </a>
       </div>
      </div>
     </div>
     <div class="hidden md:block" x-data="{ showUsMenu: false }">
      <div class="">
       <!-- desktop header nav -->
       <a class="text-white bg-orange-600 hover:bg-orange-700 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold font-xs" href="/rankings/">
        Rankings
       </a>
       <a class="text-white bg-green-800 hover:bg-green-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/players/">
        Player Profiles
       </a>
       <div class="hidden xl:inline text-white bg-green-800 hover:bg-green-900 whitespace-nowrap pr-1 py-4 no-underline m-0">
        <script>
         searchPlayers = function () {
            return {
                search: '',
                optionsVisible: false,
                playersObtained: false,
                keyPosition: -1,
                players: [{
                    n: '',
                    u: '',
                    p: ''
                }],
                selected: {
                    n: null,
                    u: null,
                    p: null
                },
                init() {
                },
                getPlayers: async function() {
                    // TODO fetch into localstorage if empty or older than an hour
                    const response = await fetch('/players/json-list');
                    this.players = await response.json();
                    this.playersObtained = true;
                },
                filtered() {
                    if (this.search === '') {
                        return;
                    }

                    if (this.players.length === 1 && !this.playersObtained) {
                        this.getPlayers();
                    }

                    let s = this.search.toLowerCase();
                    let filteredPlayers = this.players.filter((option) => {
                        if (!option.n) { // null name won't be any use
                            return;
                        }

                        return option.n.toLowerCase().includes(s) || option.p.toString().includes(s)
                    });

                    if (filteredPlayers.length > 0 && !this.selected) {
                        this.selected = filteredPlayers[0];
                    }

                    return filteredPlayers;
                },
                changeKeyPosition($el, selector, direction) {
                    if(typeof $el.querySelectorAll(selector) === 'undefined') {
                        return;
                    }

                    if($el.querySelectorAll(selector).length === 0) {
                        return;
                    }

                    if(direction == 'up') {
                        this.keyPosition--;
                    } else if(direction == 'down') {
                        this.keyPosition++;
                    }

                    if (this.keyPosition < -1) {
                        this.keyPosition = -1;
                    }

                    if (this.keyPosition > 100) {
                        this.keyPosition = 100;
                    }

                    if (this.keyPosition >= 0) {
                        $el.querySelectorAll(selector)[this.keyPosition].focus();
                    }
                }
            }
        };
        </script>
        <style>
         div#searchPlayers a.arrowKeyFocus:focus {
        background-color: #ddd;
    }
        </style>
        <div class="inline-block text-black" id="searchPlayers" x-data="searchPlayers">
         <input :value="selected.n" id="chosen" name="chosen" type="hidden"/>
         <input :value="selected.n" autocomplete="off" class="mx-auto m-0 p-2 text-sm w-24" options="" optionsvisible="!optionsVisible;" placeholder="Search" selected="selected" settimeout="" type="text" x-show="!optionsVisible"/>
         <div class="mx-auto" style="display:none;" x-show="optionsVisible">
          <input autocomplete="off" class="mx-auto p-2 text-sm" id="playerSearch" placeholder="Search" type="text" x-model.debounce="search"/>
          <div class="overflow-y-scroll absolute bg-neutral-100 border border-neutral-400 min-w-max text-left" style="max-height: 50vh; z-index: 1;">
           <template x-for="option in filtered()">
            <a :href="'/player/' + option.u + '/profile'" class="first:border brder border-b-1 border-gray-300 border-collapse pl-4 pr-6 py-2 block cursor-pointer no-underline arrowKeyFocus" x-text="option.n + ' #' + option.p" xxxclick.prevent="selected = option; optionsVisible = false">
            </a>
           </template>
          </div>
         </div>
        </div>
       </div>
       <a class="hidden xl:inline text-white bg-red-800 hover:bg-red-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/monday/">
        Monday
       </a>
       <a class="hidden xl:inline text-white bg-blue-800 hover:bg-blue-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/head-to-head">
        Head-to-Head
       </a>
       <a class="hidden xl:inline text-white bg-purple-800 hover:bg-purple-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/stats/">
        StatZone
       </a>
       <button class="ml-4 items-center px-2 py-1 border border-neutral-500 rounded text-white hover:border-white">
        More
       </button>
       <!-- desktop header nav "more" -->
       <div class="relative">
        <div class="flex flex-col bg-white absolute right-0" style="display: none;" x-show="showUsMenu">
         <a class="block xl:hidden text-white bg-red-800 hover:bg-red-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/monday/">
          Monday
         </a>
         <a class="block xl:hidden text-white bg-blue-800 hover:bg-blue-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/head-to-head">
          Head-to-Head
         </a>
         <a class="block xl:hidden text-white bg-purple-800 hover:bg-purple-900 whitespace-nowrap px-2 xl:px-4 py-4 uppercase no-underline font-bold" href="/stats/">
          StatZone
         </a>
         <div class="p-4 border border-neutral-400 flex flex-col">
          <a class="text-black hover:text-neutral-800" href="/data-fix/">
           Data Fix Portal
          </a>
          <a class="text-black hover:text-neutral-800" href="/contact-us/">
           Contact Us
          </a>
          <a class="text-black hover:text-neutral-800" href="/about-us/">
           About Us
          </a>
         </div>
        </div>
       </div>
      </div>
     </div>
    </nav>
   </header>
   <main class="container-fluid w-full mx-auto box-border flex-1 mt-32 mb-16">
    <div class="w-full lg:w-6/12 mx-auto text-center mb-8">
     <h1 class="w-full text-2xl lg:w-6/12 lg:text-4xl font-bold mx-auto text-center mb-8 bg-purple-800 text-white p-6 shadow">
      Career Standard DGPT Elite Stats MPO
     </h1>
     <h4 class="text-neutral-400">
      Last Updated: 2022-11-21 18:51:19
     </h4>
     <div class="mt-8">
      Shows player data from Standard DGPT Elite in the StatMando database that include an MPO Division, with players who cashed once.
     </div>
    </div>
    <div class="overflow-x-auto lg:overflow-x-visible w-full lg:w-11/12 mx-auto">
     <table class="border border-collapse border-t-8 border-neutral-700 box-border p-0 m-0" id="stats">
      <thead class="bg-neutral-300 border-neutral-900 text-neutral-900 cursor-pointer">
       <tr class="font-small p-8">
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-" id="player">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="starts">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="wins">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="podiums">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-10s">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-20s">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="avg-place">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="dnfs">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="win">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="podium">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-10">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-20">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="total">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="avg">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="as-winner">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="total-strokes">
        </td>
        <td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="days-since-last-win">
        </td>
       </tr>
       <tr class="font-small p-8">
        <th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-" data-filter="" data-filter-target="player">
         Player
        </th>
        <th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="starts">
         Starts
        </th>
        <th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="wins">
         Wins
        </th>
        <th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="podiums">
         Podiums

In [31]:
soup.find('table', attrs={'id':'stats'})

<table class="border border-collapse border-t-8 border-neutral-700 box-border p-0 m-0" id="stats">
<thead class="bg-neutral-300 border-neutral-900 text-neutral-900 cursor-pointer">
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-" id="player"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="starts"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="wins"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="podiums"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-10s"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-20s"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="avg-place"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="dnfs"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="win"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="podium"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-10"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="top-20"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="total"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="avg"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="as-winner"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="total-strokes"></td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap filter-search_math" id="days-since-last-win"></td>
</tr>
<tr class="font-small p-8">
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-" data-filter="" data-filter-target="player">
                        Player
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="starts">
                        Starts
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="wins">
                        Wins
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="podiums">
                        Podiums
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="top-10s">
                        Top 10s
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="top-20s">
                        Top 20s
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="avg-place">
                        Avg Place
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="dnfs">
                        DNFs
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="win">
                        Win %
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="podium">
                        Podium %
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="top-10">
                        Top 10 %
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="top-20">
                        Top 20 %
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="total">
                        Total $
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="avg">
                        Avg $
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="as-winner">
                        $ as Winner
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="total-strokes">
                        Total Strokes
                    </th>
<th class="text-left py-2 px-4 text-sm whitespace-nowrap filters filter-search_math" data-filter="search_math" data-filter-target="days-since-last-win">
                        Days Since Last Win
                    </th>
</tr>
</thead>
<tbody>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/ricky-wysocki/profile">Ricky Wysocki</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                62
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                17
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                32
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                52
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                59
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                6.18
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                1
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                27.87
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                52.46
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                85.25
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                96.72
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                169,116
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2,772
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                92,970
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                11,167
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                64
                                            </td>
</tr>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/paul-mcbeth/profile">Paul McBeth</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                61
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                16
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                34
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                51
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                59
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                5.53
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                1
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                26.67
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                56.67
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                85.00
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                98.33
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                157,503
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2,625
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                67,535
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                10,872
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                253
                                            </td>
</tr>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/eagle-mcmahon/profile">Eagle McMahon</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                40
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                7
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                18
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                29
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                33
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                8.34
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                18.42
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                47.37
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                76.32
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                86.84
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                84,948
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2,235
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                35,526
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                6,771
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                484
                                            </td>
</tr>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/calvin-heimburg/profile">Calvin Heimburg</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                49
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                5
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                17
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                32
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                43
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                9.69
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                0
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                10.20
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                34.69
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                65.31
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                87.76
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                107,976
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2,204
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                31,350
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                9,151
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                113
                                            </td>
</tr>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/simon-lizotte/profile">Simon Lizotte</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                42
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                5
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                15
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                30
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                32
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                11.83
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                1
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                12.20
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                36.59
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                73.17
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                78.05
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                95,820
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2,337
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                46,700
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                7,592
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                57
                                            </td>
</tr>
<tr class="font-small p-8">
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
<a href="/player/james-conrad/profile">James Conrad</a>
</td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                64
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                2
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                6
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                31
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">
                                                46
                                            </td>
<td class="text-left py-2 px-4 text-sm whitespace-nowrap">

In [32]:
table_html = str(soup.find('table', attrs={'id':'stats'}))

HTML(table_html)

In [33]:
player_stats_career = pd.read_html(str(soup.find('table', attrs={'id':'stats'})))[0]
player_stats_career

,Player,Starts,Wins,Podiums,Top 10s,Top 20s,Avg Place,DNFs,Win %,Podium %,Top 10 %,Top 20 %,Total $,Avg $,$ as Winner,Total Strokes,Days Since Last Win
0,Ricky Wysocki,62,17,32,52,59,6.18,1,27.87,52.46,85.25,96.72,169116,2772,92970,11167,64
1,Paul McBeth,61,16,34,51,59,5.53,1,26.67,56.67,85.00,98.33,157503,2625,67535,10872,253
2,Eagle McMahon,40,7,18,29,33,8.34,2,18.42,47.37,76.32,86.84,84948,2235,35526,6771,484
3,Calvin Heimburg,49,5,17,32,43,9.69,0,10.20,34.69,65.31,87.76,107976,2204,31350,9151,113
4,Simon Lizotte,42,5,15,30,32,11.83,1,12.20,36.59,73.17,78.05,95820,2337,46700,7592,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Alex Geisinger,5,0,0,4,4,14.60,0,0.00,0.00,80.00,80.00,6014,1203,0,1029,0
116,Karl Johan Nybo,4,0,0,2,3,14.25,0,0.00,0.00,50.00,75.00,4418,1105,0,839,0
117,Øyvind Jarnes,3,0,0,1,1,22.00,1,0.00,0.00,50.00,50.00,1550,775,0,415,0
118,Bo Tillman,3,0,0,1,2,14.67,0,0.00,0.00,33.33,66.67,2143,714,0,503,0
119,Avery Jenkins,2,0,0,1,2,8.50,0,0.00,0.00,50.00,100.00,1833,917,0,345,0

In [34]:
player_stats_career.to_csv('../data/dpgt-mpo-career-stats.csv')